execution:
- concurrency: 10
  ramp-up: 1m
  hold-for: 1m30s
  scenario: simple

scenarios:
  simple:
    requests:
         - http://54.187.115.1:8080/greeting
         - http://54.187.115.1:8080/greeting?name=varun
reporting:
- module: final-stats
  dump-xml: stats.xml 
