execution:
- concurrency: 10
  ramp-up: 1m
  hold-for: 1m30s
  scenario: simple

scenarios:
  simple:
    think-time: 0.75
    requests:
<<<<<<< HEAD
         - http://34.222.73.223:8080/greeting
         - http://34.222.73.223:8080/greeting?user=varun
=======
         - http://34.220.140.162:8080/greeting
>>>>>>> b7d048ac94591b82ddf0eb153cf2f3e4ecc742dd
reporting:
- module: final-stats
  dump-xml: stats.xml 
