execution:
- concurrency: 10
  ramp-up: 1m
  hold-for: 1m30s
  scenario: simple

scenarios:
  simple:
    requests:
         - https://answersqc.nielsen.com/portal/rsi/branding/values?branding_keys=EMBED_LOGIN_VIDEO,LOGIN_VIDEO_TITLE&locale=en_US&_=1584336219162
reporting:
- module: final-stats
  dump-xml: stats.xml 
