execution:
- concurrency: 10
  ramp-up: 1m
  hold-for: 1m30s
  scenario: simple

scenarios:
  simple:
    think-time: 0.75
    requests:
         - http://34.222.73.223:8080/greeting
         - http://34.222.73.223:8080/greeting?user=varun
reporting:
- module: final-stats
  dump-xml: stats.xml 